spring.application.name=roadmap-backend

# لو في Railway variables → استخدمهم
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/roadmap_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Roadmap@2026}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.forward-headers-strategy=framework
server.port=${PORT:8080}